kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-powervs-block-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: ibm-powervs-block-csi-driver-node-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: ibm-powervs-block-privileged-role
  apiGroup: rbac.authorization.k8s.io
