apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: powervs.csi.ibm.com
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
