apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: ibm-powervs-block-csi-driver-operator.v4.12.0
  namespace: placeholder
  annotations:
    categories: Storage
    "operatorframework.io/suggested-namespace": openshift-cluster-csi-drivers
    capabilities: Full Lifecycle
    containerImage: quay.io/mchellam/origin-ibm-powervs-block-csi-driver-operator:latest
    support: Red Hat
    operators.openshift.io/infrastructure-features: '["csi"]'
    repository: https://github.com/madhan-swe/ibm-powervs-block-csi-driver-operator-temp
    createdAt: "2021-07-14T00:00:00Z"
    description: Install and configure IBM PowerVS Block CSI driver.
    olm.skipRange: ">=4.9.0 <4.12.0"
  labels:
    operator-metering: "true"
    "operatorframework.io/arch.ppc64le": supported
spec:
  displayName: IBM PowerVS Block CSI Driver Operator
  description: Operator that installs and configures the CSI driver for IBM Power Systems(IBM PowerVS Block Volumes).
  icon:
    - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
      mediatype: image/svg+xml
  keywords:
    - storage
    - powervs
    - ibm
  links:
    - name: Documentation
      url: https://github.com/openshift/ibm-powervs-block-csi-driver-operator
    - name: Source Repository
      url: https://github.com/openshift/ibm-powervs-block-csi-driver-operator
  version: 4.12.0
  maturity: stable
  maintainers:
    - email: aos-storage-staff@redhat.com
      name: Red Hat
  minKubeVersion: 1.21.0
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: ibm-powervs-block-csi-driver-operator
    alm-status-descriptors: ibm-powervs-block-csi-driver-operator.v4.12.0
  selector:
    matchLabels:
      alm-owner-metering: ibm-powervs-block-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - rules:
          - apiGroups:
            - ''
            resources:
            - pods
            - services
            - endpoints
            - events
            - configmaps
            - secrets
            verbs:
            - '*'
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            verbs:
            - '*'
          - apiGroups:
            - monitoring.coreos.com
            resources:
            - servicemonitors
            verbs:
            - '*'
          serviceAccountName: ibm-powervs-block-csi-driver-operator
      clusterPermissions:
        - rules:
          - apiGroups:
            - security.openshift.io
            resourceNames:
            - privileged
            resources:
            - securitycontextconstraints
            verbs:
            - use
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers
            verbs:
            - get
            - list
            - watch
            # The Config Observer controller updates the CR's spec
            - update
            - patch
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers/status
            verbs:
            - get
            - list
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resourceNames:
            - extension-apiserver-authentication
            - ibm-powervs-block-csi-driver-operator-lock
            resources:
            - configmaps
            verbs:
            - '*'
          - apiGroups:
            - rbac.authorization.k8s.io
            resources:
            - clusterroles
            - clusterrolebindings
            - roles
            - rolebindings
            verbs:
            - watch
            - list
            - get
            - create
            - delete
            - patch
            - update
          - apiGroups:
            - ''
            resources:
            - serviceaccounts
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - coordination.k8s.io
            resources:
            - leases
            verbs:
            - '*'
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - ''
            resources:
            - persistentvolumes
            verbs:
            - create
            - delete
            - list
            - get
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resources:
            - persistentvolumeclaims
            verbs:
            - get
            - list
            - watch
            - update
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments
            verbs:
            - get
            - list
            - watch
            - update
            - delete
            - create
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments/status
            verbs:
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            - csinodes
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - '*'
            resources:
            - events
            verbs:
            - get
            - patch
            - create
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - storage.k8s.io
            resources:
            - csidrivers
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - cloudcredential.openshift.io
            resources:
            - credentialsrequests
            verbs:
            - '*'
          - apiGroups:
            - config.openshift.io
            resources:
            - infrastructures
            - proxies
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - authentication.k8s.io
            resources:
            - tokenreviews
            verbs:
            - create
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
            - list
            - watch
          serviceAccountName: ibm-powervs-block-csi-driver-operator
      deployments:
        - name: ibm-powervs-block-csi-driver-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ibm-powervs-block-csi-driver-operator
            template:
              metadata:
                annotations:
                  target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
                labels:
                  app: ibm-powervs-block-csi-driver-operator
              spec:
                serviceAccountName: ibm-powervs-block-csi-driver-operator
                containers:
                - name: ibm-powervs-block-csi-driver-operator
                  image: rcmadhankumar/ibm-powervs-block-csi-driver-operator:latest
                  imagePullPolicy: IfNotPresent
                  args:
                    - "start"
                    - "-v=2"
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: DRIVER_IMAGE
                      value: gcr.io/k8s-staging-cloud-provider-ibm/ibm-powervs-block-csi-driver:v0.1.0-alpha.3
                    - name: PROVISIONER_IMAGE
                      value: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
                    - name: ATTACHER_IMAGE
                      value: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
                    - name: RESIZER_IMAGE
                      value: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
                    - name: NODE_DRIVER_REGISTRAR_IMAGE
                      value: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
                    - name: LIVENESS_PROBE_IMAGE
                      value: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
                    - name: OPERATOR_NAME
                      value: ibm-powervs-block-csi-driver-operator
                    - name: KUBE_RBAC_PROXY_IMAGE
                      value: quay.io/brancz/kube-rbac-proxy:v0.12.0
                  resources:
                    requests:
                      memory: 50Mi
                      cpu: 10m
                priorityClassName: system-cluster-critical
                nodeSelector:
                  node-role.kubernetes.io/master: ""
                tolerations:
                  - key: CriticalAddonsOnly
                    operator: Exists
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: "NoSchedule"